/**
 * Pre-build script: fetches SEC company tickers and writes a compact
 * TypeScript module that gets compiled into the Worker bundle.
 *
 * Usage:  npx tsx scripts/fetch-tickers.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SEC_URL = 'https://www.sec.gov/files/company_tickers.json';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/worker/ticker-data.ts');

interface SecTicker {
  cik_str: number;
  ticker: string;
  title: string;
}

async function main() {
  console.log('Fetching SEC company tickers...');
  const res = await fetch(SEC_URL, {
    headers: {
      'User-Agent': 'jev-regime-screener/1.0 (matthew.scott.hendricks@gmail.com)',
      Accept: 'application/json',
    },
  });

  if (!res.ok) {
    throw new Error(`SEC fetch failed: ${res.status} ${res.statusText}`);
  }

  const data = (await res.json()) as Record<string, SecTicker>;

  // Deduplicate by uppercase symbol, keep first occurrence.
  const seen = new Set<string>();
  const tickers: { symbol: string; name: string }[] = [];

  for (const val of Object.values(data)) {
    const symbol = val.ticker.toUpperCase();
    if (seen.has(symbol)) continue;
    seen.add(symbol);
    tickers.push({ symbol, name: val.title });
  }

  // Sort for stable diffs.
  tickers.sort((a, b) => a.symbol.localeCompare(b.symbol));

  const lines = [
    '// Auto-generated by scripts/fetch-tickers.ts — do not edit manually.',
    `// ${tickers.length} unique tickers fetched from SEC on ${new Date().toISOString().slice(0, 10)}.`,
    '',
    'export const TICKERS: ReadonlyArray<{ symbol: string; name: string }> = [',
  ];

  for (const t of tickers) {
    // Escape any quotes in the company name.
    const name = t.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    lines.push(`  { symbol: '${t.symbol}', name: '${name}' },`);
  }

  lines.push('];');
  lines.push('');

  writeFileSync(OUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${tickers.length} tickers to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
